import { Call } from '@wailsio/runtime';

export const ExampleApi = {
  Hello(name: string) {
    return Call('ExampleApi.Hello', name);
  },
};

export const LcuApi = {
  GetAuthInfo() {
    return Call('LcuApi.GetAuthInfo');
  },
  GetCurrentSummoner() {
    return Call('LcuApi.GetCurrentSummoner');
  },
  StartClient() {
    return Call('LcuApi.StartClient');
  },
};

// Placeholder exports for existing services. These will be generated by Wails
after build.
export const MessageService: any = {};
export const GreetService: any = {};
export const ClientService: any = {};
export const HttpService: any = {};
export const OpenWindow: any = {};
