// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function Hello(name: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1364835943, name) as any;
    return $resultPromise;
}

export function ID(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2678152140) as any;
    return $resultPromise;
}
