// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WailsAPI from "./wailsapi.js";
export {
    WailsAPI
};

export * from "./models.js";
