// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class AuthInfo {
    "port": number;
    "token": string;

    /** Creates a new AuthInfo instance. */
    constructor($$source: Partial<AuthInfo> = {}) {
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthInfo($$parsedSource as Partial<AuthInfo>);
    }
}

export class SummonerInfo {
    "displayName": string;
    "profileIconId": number;
    "region": string;

    /** Creates a new SummonerInfo instance. */
    constructor($$source: Partial<SummonerInfo> = {}) {
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("profileIconId" in $$source)) {
            this["profileIconId"] = 0;
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SummonerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SummonerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SummonerInfo($$parsedSource as Partial<SummonerInfo>);
    }
}
