// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function Hello(name: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(273124019, name) as any;
    return $resultPromise;
}

export function ID(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3457447112) as any;
    return $resultPromise;
}
