// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LcuApiWails exposes only methods intended for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * GetClientPath forwards the call to the underlying service.
 */
export function GetClientPath(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4150102446) as any;
    return $resultPromise;
}

export function StartClient(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(445256185) as any;
    return $resultPromise;
}
