// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gin$0 from "../../../../github.com/gin-gonic/gin/models.js";

export function AcceptGame(ctx: gin$0.Context | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1651914924, ctx) as any;
    return $resultPromise;
}

export function GetClientPath(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2087862042) as any;
    return $resultPromise;
}

export function GetCurrSummoner(ctx: gin$0.Context | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4017525206, ctx) as any;
    return $resultPromise;
}

export function ListGamesByPUUID(ctx: gin$0.Context | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2684991563, ctx) as any;
    return $resultPromise;
}

export function ListRecentMatches(ctx: gin$0.Context | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1880795730, ctx) as any;
    return $resultPromise;
}

/**
 * Wails 服务名称
 */
export function Name(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3158049013) as any;
    return $resultPromise;
}

export function QuerySummonerByName(ctx: gin$0.Context | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3785643128, ctx) as any;
    return $resultPromise;
}

/**
 * 注册 Gin 路由
 */
export function RegisterGin(group: gin$0.IRoutes): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3269523879, group) as any;
    return $resultPromise;
}
