// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClientService exposes League of Legends client related functions to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function GetClientPath(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3855247928) as any;
    return $resultPromise;
}

export function StartClient(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3526024695) as any;
    return $resultPromise;
}

export function GetConcurrency(): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2350127255) as any;
    return $resultPromise;
}

export function SaveConcurrency(arg0: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2057276356, arg0) as any;
    return $resultPromise;
}
