// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function GetClientPath(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(0) as any; // ID will be generated
    return $resultPromise;
}

export function StartClient(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(0) as any; // ID will be generated
    return $resultPromise;
}
