// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function Greet(name: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2690019119, name) as any;
    return $resultPromise;
}

/**
 * 设置主题
 */
export function SetTheme(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4187087323) as any;
    return $resultPromise;
}
