// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * 测试在Service中http-GET请求
 */
export function GetData(param: string): Promise<any> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1582228257, param) as any;
    return $resultPromise;
}

/**
 * 测试在Service中http-POST请求
 */
export function PostData(param: string): Promise<any> & { cancel(): void } {
    let $resultPromise = $Call.ByID(745341113, param) as any;
    return $resultPromise;
}
