// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function CheckLogin(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3719369374) as any;
    return $resultPromise;
}
