// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LcuService exposes LCU related helpers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function CheckLogin(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3719369374) as any;
    return $resultPromise;
}

export function GetCredentials(): Promise<{port: string, token: string}> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2781735375) as any;
    return $resultPromise;
}
