// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * 信息对话框
 */
export function Dialog(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3875223868) as any;
    return $resultPromise;
}
