// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class MatchBrief {
    "id": number;
    "result": string;
    "mode": string;
    "kills": number;
    "deaths": number;
    "assists": number;
    "cs": number;
    "gold": number;
    "time": string;
    "level": number;
    "champion": string;
    "spells": string[];
    "items": string[];
    "map": string;

    /** Creates a new MatchBrief instance. */
    constructor($$source: Partial<MatchBrief> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("kills" in $$source)) {
            this["kills"] = 0;
        }
        if (!("deaths" in $$source)) {
            this["deaths"] = 0;
        }
        if (!("assists" in $$source)) {
            this["assists"] = 0;
        }
        if (!("cs" in $$source)) {
            this["cs"] = 0;
        }
        if (!("gold" in $$source)) {
            this["gold"] = 0;
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }
        if (!("champion" in $$source)) {
            this["champion"] = "";
        }
        if (!("spells" in $$source)) {
            this["spells"] = [];
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("map" in $$source)) {
            this["map"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchBrief instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchBrief {
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("spells" in $$parsedSource) {
            $$parsedSource["spells"] = $$createField11_0($$parsedSource["spells"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField12_0($$parsedSource["items"]);
        }
        return new MatchBrief($$parsedSource as Partial<MatchBrief>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
