// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class MatchBrief {
    "id": number;
    "result": string;
    "mode": string;
    "mode_detail": string;
    "kills": number;
    "deaths": number;
    "assists": number;
    "cs": number;
    "gold": number;
    "time": string;
    "level": number;
    "champion": string;
    "spells": string[];
    "items": string[];
    "map": string;

    /** Creates a new MatchBrief instance. */
    constructor($$source: Partial<MatchBrief> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("mode_detail" in $$source)) {
            this["mode_detail"] = "";
        }
        if (!("kills" in $$source)) {
            this["kills"] = 0;
        }
        if (!("deaths" in $$source)) {
            this["deaths"] = 0;
        }
        if (!("assists" in $$source)) {
            this["assists"] = 0;
        }
        if (!("cs" in $$source)) {
            this["cs"] = 0;
        }
        if (!("gold" in $$source)) {
            this["gold"] = 0;
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }
        if (!("champion" in $$source)) {
            this["champion"] = "";
        }
        if (!("spells" in $$source)) {
            this["spells"] = [];
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("map" in $$source)) {
            this["map"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchBrief instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchBrief {
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("spells" in $$parsedSource) {
            $$parsedSource["spells"] = $$createField12_0($$parsedSource["spells"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField13_0($$parsedSource["items"]);
        }
        return new MatchBrief($$parsedSource as Partial<MatchBrief>);
    }
}

export class RankSummary {
    "type": string;
    "total": number;
    "rate": string;
    "wins": number;
    "loses": number;
    "rank": string;
    "lp": number;
    "seasonMax": string;
    "lastSeason": string;

    /** Creates a new RankSummary instance. */
    constructor($$source: Partial<RankSummary> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("rate" in $$source)) {
            this["rate"] = "";
        }
        if (!("wins" in $$source)) {
            this["wins"] = 0;
        }
        if (!("loses" in $$source)) {
            this["loses"] = 0;
        }
        if (!("rank" in $$source)) {
            this["rank"] = "";
        }
        if (!("lp" in $$source)) {
            this["lp"] = 0;
        }
        if (!("seasonMax" in $$source)) {
            this["seasonMax"] = "";
        }
        if (!("lastSeason" in $$source)) {
            this["lastSeason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): RankSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RankSummary($$parsedSource as Partial<RankSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
