// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * 可被前端调用的方法
 */
export function Greet(name: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3970323729, name) as any;
    return $resultPromise;
}

/**
 * 实现 application.Service 接口
 */
export function Name(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1267482323) as any;
    return $resultPromise;
}

/**
 * 设置主题（用于测试窗口操作）
 */
export function SetTheme(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(549930405) as any;
    return $resultPromise;
}
