// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gin$0 from "../../../../github.com/gin-gonic/gin/models.js";

export function Hello(ctx: gin$0.Context | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3728698948, ctx) as any;
    return $resultPromise;
}

export function Name(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(506809039) as any;
    return $resultPromise;
}

export function RegisterGin(group: gin$0.IRoutes): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4212446801, group) as any;
    return $resultPromise;
}

/**
 * 可以扩展更多业务方法
 */
export function SetTheme(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3697324217) as any;
    return $resultPromise;
}
