// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetSvcWails exposes only methods intended for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * Name returns the service name.
 */
export function Name(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3230066591) as any;
    return $resultPromise;
}

/**
 * SetTheme forwards the call to the underlying service.
 */
export function SetTheme(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3063170729) as any;
    return $resultPromise;
}
